/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class de_jurihock_voicesmith_dsp_dafx_NativeTimescaleProcessor */

#ifndef _Included_de_jurihock_voicesmith_dsp_dafx_NativeTimescaleProcessor
#define _Included_de_jurihock_voicesmith_dsp_dafx_NativeTimescaleProcessor
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     de_jurihock_voicesmith_dsp_dafx_NativeTimescaleProcessor
 * Method:    alloc
 * Signature: (III)J
 */
JNIEXPORT jlong JNICALL Java_de_jurihock_voicesmith_dsp_dafx_NativeTimescaleProcessor_alloc
  (JNIEnv *, jobject, jint, jint, jint);

/*
 * Class:     de_jurihock_voicesmith_dsp_dafx_NativeTimescaleProcessor
 * Method:    free
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_de_jurihock_voicesmith_dsp_dafx_NativeTimescaleProcessor_free
  (JNIEnv *, jobject, jlong);

/*
 * Class:     de_jurihock_voicesmith_dsp_dafx_NativeTimescaleProcessor
 * Method:    processFrame
 * Signature: (J[F)V
 */
JNIEXPORT void JNICALL Java_de_jurihock_voicesmith_dsp_dafx_NativeTimescaleProcessor_processFrame
  (JNIEnv *, jobject, jlong, jfloatArray);

#ifdef __cplusplus
}
#endif
#endif
