/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class de_jurihock_voicesmith_dsp_KissFFT */

#ifndef _Included_de_jurihock_voicesmith_dsp_KissFFT
#define _Included_de_jurihock_voicesmith_dsp_KissFFT
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     de_jurihock_voicesmith_dsp_KissFFT
 * Method:    alloc
 * Signature: (I)J
 */
JNIEXPORT jlong JNICALL Java_de_jurihock_voicesmith_dsp_KissFFT_alloc
  (JNIEnv *, jobject, jint);

/*
 * Class:     de_jurihock_voicesmith_dsp_KissFFT
 * Method:    free
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_de_jurihock_voicesmith_dsp_KissFFT_free
  (JNIEnv *, jobject, jlong);

/*
 * Class:     de_jurihock_voicesmith_dsp_KissFFT
 * Method:    fft
 * Signature: (J[F)V
 */
JNIEXPORT void JNICALL Java_de_jurihock_voicesmith_dsp_KissFFT_fft
  (JNIEnv *, jobject, jlong, jfloatArray);

/*
 * Class:     de_jurihock_voicesmith_dsp_KissFFT
 * Method:    ifft
 * Signature: (J[F)V
 */
JNIEXPORT void JNICALL Java_de_jurihock_voicesmith_dsp_KissFFT_ifft
  (JNIEnv *, jobject, jlong, jfloatArray);

#ifdef __cplusplus
}
#endif
#endif
