/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class de_jurihock_voicesmith_dsp_processors_NativeResampleProcessor */

#ifndef _Included_de_jurihock_voicesmith_dsp_processors_NativeResampleProcessor
#define _Included_de_jurihock_voicesmith_dsp_processors_NativeResampleProcessor
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     de_jurihock_voicesmith_dsp_processors_NativeResampleProcessor
 * Method:    alloc
 * Signature: (II)J
 */
JNIEXPORT jlong JNICALL Java_de_jurihock_voicesmith_dsp_processors_NativeResampleProcessor_alloc
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     de_jurihock_voicesmith_dsp_processors_NativeResampleProcessor
 * Method:    free
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_de_jurihock_voicesmith_dsp_processors_NativeResampleProcessor_free
  (JNIEnv *, jobject, jlong);

/*
 * Class:     de_jurihock_voicesmith_dsp_processors_NativeResampleProcessor
 * Method:    processFrame
 * Signature: (J[F[F)V
 */
JNIEXPORT void JNICALL Java_de_jurihock_voicesmith_dsp_processors_NativeResampleProcessor_processFrame
  (JNIEnv *, jobject, jlong, jfloatArray, jfloatArray);

#ifdef __cplusplus
}
#endif
#endif
